### PR TITLE
Added Contribution endpoint + minor changes in EHR , DIRECTORY, TEMPLATE

### PR DESCRIPTION
**Pull request by bjornna**
I have added a definition of a CONTRIBUTION endpoint. 

There is also some minor changes on EHR, DIRECTORY and TEMPLATE. 

Also added .gitignore to make sure no HTML files are added in REST_API folder

### CODE REVIEW

**Comment by bjornna** [comment]
@ppazos - I think there must be someting wrong with my proposal then. The idea here is to commit everything in the same request/transaction. Put another way; the POSTed contribution contains the CONTRIBUTION with all its content inside. This makes it more clean when i.e. committing more than one Composition in an application based transaction. 

The idea was NOT to do two requests; 1) POST composition and 2) POST contribution. That would be a bad idea.

**Comment by ppazos** [comment]
@bjornna in that case, I think having all in POST /ehr/{ehrId}/compositions is clearer, and that endpoint already exists. 

Need to double check the request body and params to see if contribution info is included in POST /ehr/{ehrId}/compositions maybe spec is incomplete.

**Comment by bjornna** [comment]
@ppazos - what if you want to commit a FOLDER with two COMPOSITIONs in one request? 

I think it is cleaner to make all commits into an openEHR system through the contribution endpoint. 

And this may even be an argument for dropping POST /ehr/{ehrId}/compositions . 
Let's discuss this in the meeting tomorrow.

**Comment by ppazos** [comment]
@bjornna I think creating folders and associating compositions with folders are separate transactions than committing compositions to an ehr.

We need to define the criteria here.

Consider folders can be created at any time, before or after compositions are created (even months before or after), so it makes sense to commit compositions and folders on their own contributions, and having an extra endpoint to associate compositions to folders, like PUT .../folders/{fuid}/items/{compouid}

In the specific case folders and compositions are created at the same time, internally can be committed and associated using the same endpoints mentioned above.

**Comment by ppazos** [comment]
@bjornna Also, there is something to consider when committing canonical versions in XML: all the versions need to have the contribution object ref inside, having 10 compos for the same contribution will include the same object ref 10 times.

I proposed to have that implicitly by relaxing the schema a little, but maybe this proposal wasn't well explained by me, please check https://openehr.atlassian.net/browse/SPECPR-105

**Pull request merged**
